### ISSUE TITLE
Your website is having issues loading

### ISSUE THREAD

**Issue by teebu** [wimpyprogrammer/regex-to-strings#112]
This report isnt about your code, but I love using your website to expand regex strings and its been broken for a while.

https://www.wimpyprogrammer.com/regex-to-strings

**Comment by wimpyprogrammer** [comment]
Thanks for the heads up!  It looks like the polyfill service I was using, [polyfill.app](https://polyfill.app/), is down.  For now I've removed the polyfill so the page is back online but might be broken in some older browsers.

I'll also try to find a simple uptime monitor that can alert me if the page goes down for an extended time.

Thanks again!
